### ISSUE TITLE
Error when using toagent

### ISSUE THREAD

**Issue by avinashacco** [danielstjules/toragent#1]
Unhandled rejection Error: undefined
    at Object.ensureErrorObject (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\openports\node_modules\bluebird\js\main\util.js:261:20)
    at Promise._rejectUncheckedCheckError (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\openports\node_modules\bluebird\js\main\promise.js:660:22)
    at Promise._settlePromiseAt (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\node_modules\bluebird\js\main\promise.js:582:21)
    at Promise._settlePromises (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback](timers.js:525:5)
Unhandled rejection Error: undefined
    at ChildProcess.<anonymous> (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:64:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Function.Tor.spawn (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:29:10)
    at Timeout._onTimeout (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:42:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
Unhandled rejection Error: undefined
    at ChildProcess.<anonymous> (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:64:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
From previous event:
    at Function.Tor.spawn (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:29:10)
    at Timeout._onTimeout (C:\Users\Avinash V\Documents\Junk\jumpermedia\node_modules\toragent\lib\tor.js:42:23)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

**Comment by danielstjules** [comment]
Looks like tor is being closed before the connection can even be made. Have you successfully ran tor on your windows machine before? Otherwise could be a windows compat issue, sorry
